### ISSUE TITLE
Defaults differ depending on base URL being set or not, should they?

### ISSUE THREAD

**Issue by 43081j** [WICG/urlpattern#63] opened 2021-07-28 21:32 UTC
Taking this from kenchris/urlpattern-polyfill#26

It may well be a non-issue but i figured i should at least raise it still.

```ts
new URLPattern({}); // all parts are wildcard
new URLPattern({ baseURL }); // all parts not specified in the base URL are exact matches of empty strings, no wildcards
```

This difference in behaviour confused me so may confuse others, too.

We need to support empty strings as values, but maybe we could treat them as wildcards during conversion/parsing of a base URL?

Presumably under the hood, passing a base URL results in it being parsed (probably via URL) and we then assign each part (property) to the `URLPattern`. At that point, maybe we could assign empty strings as wildcards?

Another example:

```ts
new URLPattern({ baseURL: 'https://example.com' })
// results in a pattern object:
{
  hostname: "example.com",
  protocol: "https",
  pathname: "/",
  port: "",
  username: "",
  search: "",
  password: "",
  hash: ""
}
```

Meanwhile:

```ts
new URLPattern({
  hostname: 'example.com',
  protocol: 'https',
  pathname: '/'
});
// results in a pattern object:
{
  hostname: 'example.com',
  protocol: 'https',
  pathname: '/',
  port: '*',
  username: '*',
  search: '*',
  password: '*',
  hash: '*'
}
```

If we considered empty values in base URLs as wild cards, these two would behave the same.

In real world, i think its likely someone might try this:

```ts
new URLPattern({
  pathname: '/user/:id',
  baseURL: 'https://example.com/'
})
```

But consider how that'd then work:

```ts
pattern.test("https://example.com/user/123"); // true
pattern.test("https://example.com/user/123?foo=bar"); // false
pattern.test("https://example.com/user/123#foo"); // false
```

if you think its better how it currently works, thats also fine but please do document the behaviour difference well, the fact that it will _not_ default to wildcards with a base url.

**Comment by wanderview** [comment] 2021-07-29 14:02
Thanks for filing this.

Documentation could probably be better, but this is documented at least a bit at:

https://github.com/WICG/urlpattern/blob/main/mdn-drafts/QUICK-REFERENCE.md#using-base-urls-in-the-urlpattern-constructor

@jeffposnick do you think we should clarify this in the web.dev post?

To the main issue here:

> If we considered empty values in base URLs as wild cards, these two would behave the same.

(Mostly repeating from our other thread for the benefit of folks here...)

The problem is there *are* no empty values in base URLs.  When you write a URL you are precisely defining a value for every component.  You may not have written a part number, but an empty string port component means something very specific.  If we coerce these values to wildcards then we would be changing the meaning of the URL in a fundamental way.  Given that components like port are part of the origin that could have security consequences.

In addition, if we coerced empty string to wildcards there would also be no way write a URLPattern that required an empty component.  We really need to support requiring an empty component, though.

At the end of the day empty strings and "missing" values are not the same.  URLs do not have "missing" components.  So a base URL will always provide at least an empty string for each component.

But we can try to document this better.  Good point.

**Comment by jeffposnick** [comment] 2021-08-02 19:54
Yup, I'm happy to get this spelled out in the web.dev post if it's causing confusion for developers.

I'll link to a PR when it's ready.

**Comment by jeffposnick** [comment] 2021-08-04 20:06
C.f. https://github.com/GoogleChrome/web.dev/pull/5925

**Comment by wanderview** [comment] 2021-08-09 21:32
Thanks @jeffposnick!  I'm going to close this for now.

**Closed by wanderview** 2021-08-09 21:32 UTC
